name: DCO Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  dco-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Check DCO
        run: |
          git log --format=%B -n 1 ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep -i "Signed-off-by" > /dev/null || (echo "No DCO found in commit message" && exit 1)
