name: DCO Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  dco-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Check DCO
        run: |
          DCO_CHECK_RESULT=$(git log --format=%b ${{ github.event.before }}..${{ github.sha }} | grep -E -i '^(Signed-off-by|Co-authored-by):')
          if [ -z "$DCO_CHECK_RESULT" ]; then
            echo "DCO check failed. Every commit must be signed off."
            exit 1
          else
            echo "DCO check passed. Every commit has been signed off."
          fi
